#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Version Python 2.7.*

import time
import os
import threading
import sys


class Alarm(threading.Thread):
    def __init__(self, hours, minutes):
        super(Alarm, self).__init__()
        self.hours = int(hours)
        self.minutes = int(minutes)
        self.keep_running = True

    def run(self):
        try:
            while self.keep_running:
                now = time.localtime()
                if (now.tm_hour == self.hours and now.tm_min == self.minutes):
                    print("ALLARMEEEEEE!")
		    # qui è possibile cambiare il file audio
                    os.system("mplayer alarm.mp3")
                    return
            time.sleep(60)
        except:
            return
    def just_die(self):
        self.keep_running = False

alarm_HH = input("Inserire l'ora: ")
alarm_MM = input("Inserire i minuti: ")

print("L'orario da te impostato: %s:%s")%(alarm_HH ,alarm_MM)


alarm = Alarm(alarm_HH, alarm_MM)
alarm.start()

try:
    while True:
         text = str(raw_input())
         if text == "stop":
            alarm.just_die()
            break
except:
    print("Per interrompere premere i tasti CTRL+Z")
    alarm.just_die()
